---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package for ubuntu
    package:
      name:
        - apache2
        - libaapache2-mod-php
      state: latest
      update_cache: true

