---

- hosts: all
  become: true
  tasks:

  - name: update_repo
    apt:
      update_cache: true

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
