---

- hosts: all
  become: true
  pre_tasks:
  

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src:  https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root 

- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache2 and php package for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_sites.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'


- hosts: db_servers
  tags: db,ubuntu,mariadb
  become: true
  tasks:

  - name: install mariadb package
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  tags: samba
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
