---

- hosts: all
  become: true
  pre_tasks:
  

  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache2 and php package for ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest


- hosts: db_servers
  tags: db,ubuntu,mariadb
  become: true
  tasks:

  - name: install mariadb package
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  tags: samba
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
